### PR TITLE
[RUSH] Set up github action

### PR DESCRIPTION
**Pull request by jigmetnamgyal**
This Pr deals with the following

1) set up for github action.
2) Updated the rule for prettier
3) Added precommit for eslint
4) Added script for prettier and eslint

- [ ] Add precommit for git-cz?? @Kzoeps didn't know how to use git-cz help needed.

### CODE REVIEW

**Review by karanurao — APPROVED** [review]
checked

**Comment by Kzoeps** [comment]
@JigmeT123 i think its better to change the actions to use yarn instead of npm. since we're using yarn for the project.
dont know if it matters or not though. Sure ill look into the pre commit check

**Comment by jigmetnamgyal** [comment]
> @JigmeT123 i think its better to change the actions to use yarn instead of npm. since we're using yarn for the project. dont know if it matters or not though. Sure ill look into the pre commit check

Ahh sure, will update it thanks.

**Review by Kzoeps — APPROVED** [review]
@JigmeT123 action works with yarn now. So keeping yarn approving it as well

**Pull request merged**
